jest-community/snapshot-diff

__tests__/__snapshots__/snapshotDiff.test.js.snap
__tests__/snapshotDiff.test.js
src/index.js

Fixes #2.
- It needs to wait for Jest to release https://github.com/facebook/jest/pull/4152
- After that release, the test snapshot will need to be updated

[ON HOLD] - Add contextLines as option

---

.npmignore

After installing `snapshot-diff` webstorm gone crazy and things that jest functions belongs to `snapshot-diff`

Do not publish `flow-typed` directory to npm

---

README.md
__tests__/__snapshots__/getSnapshotDiffSerializer.test.js.snap
__tests__/__snapshots__/snapshotDiff.test.js.snap
__tests__/__snapshots__/toMatchDiffSnapshot.test.js.snap
__tests__/getSnapshotDiffSerializer.test.js
__tests__/index.test.js
serializer.js
src/index.js

Breaking Change. Add custom diff serializer.

---

index.d.ts

This PR simply adds the required generic to the `Matcher` definition and also declares that this repo is a module.
(the module type definition might not be completely accurate. If not, let me know and I'll fix).
Without these changes, typescript will complain and likely error (depending on your configuration).

fix small issues in typescript types

---

__tests__/__snapshots__/getSnapshotDiffSerializer.test.js.snap
__tests__/__snapshots__/snapshotDiff.test.js.snap
__tests__/__snapshots__/toMatchDiffSnapshot.test.js.snap
__tests__/snapshotDiff.test.js
__tests__/toMatchDiffSnapshot.test.js
package.json
yarn.lock

(mostly to not rely on beta releases)

fix(package): update jest dependencies

---

index.d.ts

Currently `expect.extend({ toMatchDiffSnapshot });` throws:
```
TS2322: Type '(newObject: any) => void' is not assignable to type 'CustomMatcher'.
Type 'void' is not assignable to type 'CustomMatcherResult | Promise<CustomMatcherResult>'.
```

fix(index.d.ts): Use jest.CustomMatcher type for toMatchDiffSnapshot

---

README.md
__tests__/__snapshots__/toMatchDiffSnapshot.test.js.snap
__tests__/toMatchDiffSnapshot.test.js
index.d.ts
src/index.js

feat: add testName to toMatchDiffSnapshot

---

README.md

Relying less on string replacing `rootDir` is always a good thing, as that path is not necessarily true, especially in monorepos

chore: make readme example config be js

---

index.d.ts
src/index.js

The types were missing both for Flow and TS. Fixed that

fix: add types for stablePatchmarks

---

README.md
extend-expect.js

Off the back of what @kentcdodds is doing over at https://github.com/testing-library/jest-dom and its simple:
```js
// jest.config.js
module.exports = {
setupFilesAfterEnv: [
require.resolve('jest-dom/extend-expect'),
],
}
```
I aim to introduce something similar to that, that would alleviate the need for a jest setup file.
Which will allow:
```js
// jest.config.js
module.exports = {
setupFilesAfterEnv: [
require.resolve('snapshot-diff/extend-expect'),
],
}
```
Or this at the top of the spec file:
```js
import 'snapshot-diff/extend-expect';
```

feat: Simpler integration with the new setupFilesAfterEnv jest feature

---

index.d.ts

Hi,
the `Matchers` type of definitelytyped's jest package have been updated: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jest/index.d.ts#L667
This causes a compilation error since the interfaces don't match any more, e.g.
```
node_modules/snapshot-diff/index.d.ts:13:13 - error TS2428: All declarations of 'Matchers' must have identical type parameters.
13   interface Matchers<R> {
~~~~~~~~
```
There are several other similar examples e.g.
https://github.com/styled-components/jest-styled-components/pull/270
https://github.com/testing-library/jest-dom/pull/150

fix(breaking): update TS type to match latest @types/jest

---

README.md
__tests__/__snapshots__/setSerializers.test.js.snap
__tests__/setSerializers.test.js
extend-expect.js
package.json
src/index.js
src/react-serializer.js
yarn.lock

Provides new `setSerializers` function to set the serializer objects to
be used before diffing. React component serializer implementation using
`react-test-renderer` has been extracted out.
Fixes #18
Fixes #30
Fixes #31

feat: Allow custom serializers through `setSerializers`

---

index.d.ts

Adding missing TS types for `setSerializers` and `defaultSerializers`
cc @SimenB can you test that?

fix: add `setSerializers` and `defaultSerializers` to TS types

---

index.d.ts

Current type declaration for serializer causes errors when used with
`enzyme-to-json`. Changes:
* `diffOptions` is now an optional parameter (as it is in code).
* Type declaration for the second `serialize` parameter of the `print`
function has been weakened to `any` due to incorrect type used in
`enzyme-to-json` (should be function, but has been typed serializer)
* Return type declaration from `print` function has been weakened to
`any`; this function is not limited to only returning strings.
Conflicting `enzyme-to-json` declaration:
https://github.com/adriantoine/enzyme-to-json/blob/d1f86ee82ce014bb3d63f521a5d553307948eff0/index.d.ts#L22-L25
Mismatch of `enzyme-to-json` `serializer` type in `print` function:
https://github.com/adriantoine/enzyme-to-json/blob/d1f86ee82ce014bb3d63f521a5d55 …

Update serializer types to support enzyme-to-json

---

.prettierrc
extend-expect.js
package.json
prettier.config.js
yarn.lock

Needs .prettierrc
EDIT: Blocked by: https://github.com/callstack/eslint-config-callstack/pull/88

chore: upgrade `@callstack/eslint-config` to v9.1

---

package.json
src/index.js
yarn.lock

Make use of the new jest-diff options which allow color output to be
controlled. Use of example in documentation to turn off all color
output. strip-ansi is now unnecessary and has been removed as a
dependency.
Fixes #113
Documentation example: https://github.com/facebook/jest/tree/d81464622dc8857ba995ed04e121af2b3e8e33bc/packages/jest-diff#example-of-options-for-no-colors

Use jest-diff options to turn off colors in diff

---

__tests__/__snapshots__/snapshotDiff.test.js.snap
__tests__/snapshotDiff.test.js
src/react-serializer.js

Use same serializers as jest-snapshot when serializing React components
rendered by react-test-renderer.
With the React serializer updated to use `prettyFormat`, this now
supports diffing React fragments when comparing a single element to
multiple elements returned. Adding test to confirm output.
Fixes #106
Fixes #111

feat(breaking): Output jest mock function names in snapshot diff

---

.travis.yml
__tests__/__snapshots__/snapshotDiff.test.js.snap
__tests__/snapshotDiff.test.js
babel.config.js
package.json
src/index.js
yarn.lock

Also:
- dropped Node 6, 
- added engines requirement for >=10, since Jest dropped Node 8
- fixed Flow errors

chore(breaking): bump Jest to 26

---

__tests__/__snapshots__/snapshotDiff.test.js.snap
__tests__/snapshotDiff.test.js
package.json
yarn.lock

Updates to the latest jest-diff which now supports removing color codes
from "no visual difference" message. A test has been added to confirm
this and prevent regressions in the future.
This is a follow-on PR from PR #123.
There is a dependabot PR already up for this bump (PR #170) and other jest dependencies, but this PR includes a test for when there is no difference. These PRs should close automatically once this lands.
Fixes #129

Update jest-diff to remove colors from no diff message

---

package.json
src/index.js
src/react-serializer.js
yarn.lock

`jest@27` has been out for almost a month. `snapshot-diff` is the only dependency that is still referencing `@26` for us.

chore(deps): update jest to 27

---

package.json
yarn.lock

All tests pass, unsure what else should be checked?
@thymikee btw, would you be against enabling renovate and at least have the weekly lockfile refreshes? Like https://github.com/jest-community/eslint-plugin-jest/pull/1183. It keeps most "vulnerability" warnings away 🙂

feat: update Jest dependencies
